name: Deploy to Hostgator
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest,
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.action_node_version }}
      - name: Install dependencies
        run: npm install
      - name: Clean install dependencies and build
        run: npm run build
      - name: Set Folder to copy
        run: cd out
      - name: Sync Files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.NEXTJS_SITE_SERVER }}
          username: ${{ secrets.NEXTJS_SITE_USER }}
          password: ${{ secrets.NEXTJS_SITE_PASS }}
# - name: Deploy to HostGator SSH
      #   run: |
      #     mkdir -p ~/.ssh/
      #     echo "$SSH_PRIVATE_KEY" > ../private.key
      #     sudo chmod 600 ../private.key
      #     echo "$SSH_KNOW_HOSTS" > ~/.ssh/known_hosts
      #   shell: bash
      #   env: 
      #     SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      #     SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
      #     SSH_KEY_PATH: ${{ github.workspace }}/../private.key 
